# ---------------------------------------------------------------------------
# AzuriomIntegration Configuration
# This file contains the connection details for your Azuriom web store's
# database. Make sure these details match your XAMPP/MySQL setup.
# ---------------------------------------------------------------------------

database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: ""
  name: "azuriom"